#+title: Yet Another Emacs Configuration

  An online version of this doc can be found at
  https://emacs.readthedocs.io/en/latest/

  The cores of this project are
  
  - config.org :: It has the emacs configuration implemented in
    org-mode. It includes what the features is and how I use them in
    Emacs.
  - config/*.el :: files are extracted from config.org. they are
    tracked in git and can be used directly for configuring emacs.
  
** Dependencies                                                  :ExportFile:
   :PROPERTIES:
   :EXPORT_FILE_NAME: ~/git/.emacs.d/docs/install_packages
   :END:

 The configurations are tested in Emacs 26 and 27.1.

 The required packages are listed in Cask file.

* Change Log

  
** 2020 June
   
   Major restructuring update to simply this project.
   1. Unused configurations and 3rd party dependences are removed.
   2. Configurations are also tracked in config/*.el so one can use
      them directly.
   3. Reduce the load time by 40% (5.8s to 3.6s).

